# Generated by Django 5.1.1 on 2024-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
    ]
